### ISSUE TITLE
Potential conflict with Pluto?

### ISSUE THREAD

**Issue by max-sixty** [jkrumbiegel/Chain.jl#39] opened 2021-12-06 16:14 UTC
I'm new to Julia and so I might be making a naive mistake.

In Pluto, running something like this prints the docs! This may be because in pluto, the docs are offered in a pop-up on the bottom right.

```julia
@chain begin "3,4,3,1,2"
	strip
end
```
<img width="732" alt="image" src="https://user-images.githubusercontent.com/5635139/144881007-cb729fc6-63dc-4e4a-b7d0-42622c364f7e.png">

and running

```julia
@chain begin "3,4,3,1,2"
	strip
	split(",") 
end
```

returns an error

```
MethodError: no method matching split(::Base.Docs.Binding, ::String)

Closest candidates are:

split(!Matched::T, ::Any; limit, keepempty) where T<:AbstractString at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/strings/util.jl:417

    top-level scope@Local: 3[inlined]
```

It's not _purely_ a Pluto issue though — `@_` from `Underscores.jl` doesn't have this problem, maybe because it doesn't use multiple lines?

Thank you!

**Comment by max-sixty** [comment] 2021-12-06 19:49
FWIW surrounding the block with another `begin ... end` makes it work, so possibly this is more of a Pluto issue?

**Comment by jkrumbiegel** [comment] 2021-12-06 20:44
Hah I remember seeing this error once and not understanding it, but now I do. The problem is that the string `"3,4,3,1,2"` above `strip` is parsed into a docstring for the `strip` function. This happens at parse time and I can't do anything about it in my macro. You can see this if you look at the output of `Meta.@dump`:

```julia
julia> Meta.@dump @chain begin
               "3,4,3,1,2"
               strip
               split(",") 
       end
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: Symbol @chain
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[5]
    3: Expr
      head: Symbol block
      args: Array{Any}((4,))
        1: LineNumberNode
          line: Int64 2
          file: Symbol REPL[5]
        2: Expr
          head: Symbol macrocall
          args: Array{Any}((4,))
            1: GlobalRef
              mod: Module Core
              name: Symbol @doc
            2: LineNumberNode
              line: Int64 2
              file: Symbol REPL[5]
            3: String "3,4,3,1,2"
            4: Symbol strip
        3: LineNumberNode
          line: Int64 4
          file: Symbol REPL[5]
        4: Expr
          head: Symbol call
          args: Array{Any}((2,))
            1: Symbol split
            2: String ","
```

Of course, now that I think about it, I could specifically intercept this situation and re-expand the doc macro call into a string and a function..

**Comment by jkrumbiegel** [comment] 2021-12-06 20:46
The workaround is to put the string before the `begin` block to avoid the doc parsing

**Comment by max-sixty** [comment] 2021-12-07 00:02
Thanks @jkrumbiegel! I'm less familiar with how this works — should I put an issue in Pluto? Or is this unavoidable on their side too?

**Comment by jkrumbiegel** [comment] 2021-12-07 07:37
No they're just expanding the macro and finding the docstring, I could try to fix that, remove the doc string in the first line if there's one

**Comment by jkrumbiegel** [comment] 2021-12-07 09:49
Fixed in https://github.com/jkrumbiegel/Chain.jl/pull/41

**Closed as completed by jkrumbiegel** 2021-12-07 09:49 UTC
